import { bindUiEvents } from './ui.js';
import { bindRuntimeEvents } from './runtime.js';
import { bindAccessEvents } from './access.js';
import { bindKeyEvents } from './keys.js';
import { bindConnectionsEvents } from './connections.js';
import { bindProvidersEvents } from './providers.js';
import { bindBackupEvents } from './backup.js';
import { bindConfigurationEvents } from './configuration.js';
import { bindRemoteEvents } from './remote.js';
import { bindInstanceEvents, initializeAdmin } from './instances.js';
import { bindRestartEvents } from './restart.js';
import { bindRecoveryEvents } from './recovery.js';
import { state } from './state.js';
import { bindSnapshotEvents } from './snapshot.js';

state.api = window.fholdAdmin;
bindUiEvents();
bindRuntimeEvents();
bindAccessEvents();
bindKeyEvents();
bindConnectionsEvents();
bindProvidersEvents();
bindBackupEvents();
bindRecoveryEvents();
bindConfigurationEvents();
bindRemoteEvents();
bindInstanceEvents();
bindRestartEvents();
bindSnapshotEvents();
void initializeAdmin();
